apiVersion: v1
kind: ConfigMap
metadata:
  name: auctiondatamanager-config
data: 
  USERSPERAUCTIONSCALEFACTOR: "15.0"
  USERS: "1000"
  MAXUSERS: "1000"
  WORKLOADNUM: "1"
  APPINSTANCENUM: "1"
  CASSANDRA_CONTACTPOINTS: "cassandra"
  CASSANDRA_PORT: "9042"
  DBHOSTNAME: "postgresql"
  DBPORT: "5432"
  HEAP: "4G"
  THREADS: "8"
  SPRINGPROFILESACTIVE: "postgresql,ehcache,imagesInMongo,singleMongo,singleRabbit" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auctiondatamanager
  labels:
    app: auction
    tier: dataManager
    impl: auctiondatamanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction
      tier: dataManager
      impl: auctiondatamanager
  template:
    metadata:
      name: auctiondatamanager
      labels:
        app: auction
        tier: dataManager
        impl: auctiondatamanager
    spec:
      containers:
      - image: hrosenbe/weathervane-auctiondatamanager:1.2.0
        name: auctiondatamanager
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - cat
            - /loadData.pl
          initialDelaySeconds: 15
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: auctiondatamanager-config
        resources:
          requests:
            cpu: 500m
            memory: 2200Mi
            